"""Agregar campos colegio, comuna y region a Student

Revision ID: a7954187e0de
Revises: babfec4ccd06
Create Date: 2025-06-07 23:43:54.565953

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7954187e0de'
down_revision = 'babfec4ccd06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('rut', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('age', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('accepted_terms', sa.Boolean(), nullable=True))
        batch_op.create_unique_constraint('uq_admins_rut', ['rut'])

    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('colegio', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('comuna', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('region', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_column('region')
        batch_op.drop_column('comuna')
        batch_op.drop_column('colegio')

    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.drop_constraint('uq_admins_rut', type_='unique')
        batch_op.drop_column('accepted_terms')
        batch_op.drop_column('age')
        batch_op.drop_column('rut')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
